/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Tue Sep  2 16:54:08 2025


#include "GPTDevice_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(GPTDeviceParamsCOMPONENT, "yarp.device.GPTDevice")
}


GPTDevice_ParamsParser::GPTDevice_ParamsParser()
{
}


std::vector<std::string> GPTDevice_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("api_version");
    params.push_back("prompt_file");
    params.push_back("prompt_context");
    params.push_back("function_file");
    params.push_back("json_context");
    return params;
}


bool GPTDevice_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="api_version")
    {
        paramValue = m_api_version;
        return true;
    }
    if (paramName =="prompt_file")
    {
        paramValue = m_prompt_file;
        return true;
    }
    if (paramName =="prompt_context")
    {
        paramValue = m_prompt_context;
        return true;
    }
    if (paramName =="function_file")
    {
        paramValue = m_function_file;
        return true;
    }
    if (paramName =="json_context")
    {
        paramValue = m_json_context;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string GPTDevice_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      GPTDevice_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(GPTDeviceParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter api_version
    {
        if (config.check("api_version"))
        {
            m_api_version = config.find("api_version").asString();
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'api_version' using value:" << m_api_version;
        }
        else
        {
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'api_version' using DEFAULT value:" << m_api_version;
        }
        prop_check.unput("api_version");
    }

    //Parser of parameter prompt_file
    {
        if (config.check("prompt_file"))
        {
            m_prompt_file = config.find("prompt_file").asString();
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'prompt_file' using value:" << m_prompt_file;
        }
        else
        {
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'prompt_file' using DEFAULT value:" << m_prompt_file;
        }
        prop_check.unput("prompt_file");
    }

    //Parser of parameter prompt_context
    {
        if (config.check("prompt_context"))
        {
            m_prompt_context = config.find("prompt_context").asString();
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'prompt_context' using value:" << m_prompt_context;
        }
        else
        {
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'prompt_context' using DEFAULT value:" << m_prompt_context;
        }
        prop_check.unput("prompt_context");
    }

    //Parser of parameter function_file
    {
        if (config.check("function_file"))
        {
            m_function_file = config.find("function_file").asString();
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'function_file' using value:" << m_function_file;
        }
        else
        {
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'function_file' using DEFAULT value:" << m_function_file;
        }
        prop_check.unput("function_file");
    }

    //Parser of parameter json_context
    {
        if (config.check("json_context"))
        {
            m_json_context = config.find("json_context").asString();
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'json_context' using value:" << m_json_context;
        }
        else
        {
            yCInfo(GPTDeviceParamsCOMPONENT) << "Parameter 'json_context' using DEFAULT value:" << m_json_context;
        }
        prop_check.unput("json_context");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(GPTDeviceParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(GPTDeviceParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      GPTDevice_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: GPTDevice\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'api_version': The openAI APIs version to use\n");
    doc = doc + std::string("'prompt_file': The file containing the prompt for the LLM\n");
    doc = doc + std::string("'prompt_context': The yarp context from which the prompt file should be loaded\n");
    doc = doc + std::string("'function_file': The file containing the definitions of the tools for the LLM\n");
    doc = doc + std::string("'json_context': The yarp context from which the function file should be loaded\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device GPTDevice --api_version 2023-07-01-preview --prompt_file <optional_value> --prompt_context GPTDevice --function_file <optional_value> --json_context GPTDevice\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device GPTDevice\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
